name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          BATCH_IMAGE_TAG: ${{ env.COMMIT_HASH }}  # 커밋 해시 사용
          LATEST_TAG: latest
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          set -e
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$BATCH_IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$BATCH_IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BATCH_IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST_TAG

      - name: Update Kubernetes Deployment with new image
        run: |
          # Deployment YAML 파일에서 이미지 태그를 커밋 해시로 업데이트
          sed -i 's|image: .*|image: '${ECR_REGISTRY}'/'${ECR_REPOSITORY}':'${BATCH_IMAGE_TAG}|' deployment.yaml
          kubectl apply -f deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
